# Generated by Django 4.2.30 on 2026-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
